remove dependencies of pkg_resources
abeja-inc/abeja-platform-sdk pull request #55
Opened 2020-11-16 09:15 UTC by seiro-ogasawara

https://github.com/abeja-inc/platform-planning/issues/3808

た、たぶん出来てるはず

2020-11-16 09:17 UTC, seiro-ogasawara commented on abeja/version.py
> +VERSION = "2.1.0"
`pkg_resources` を使わないように修正。
`"2.1.0"` はとりあえずで入れてるけど、 CircleCI の `replace-version` で pyproject.toml に定義してあるバージョンに差し替えられます。

2020-11-16 09:18 UTC, seiro-ogasawara commented on .circleci/config.yml
> +      sed -i -e "s/VERSION = \".*\"/VERSION = \"$ver\"/" abeja/version.py
pyproject.toml に記載のバージョンを使って abeja/version.py の中身を差し替え

2020-11-16 09:23 UTC, seiro-ogasawara commented on .circleci/config.yml
> +  - run: poetry version "$(PYTHONPATH=./ poetry version | cut -d ' ' -f 2)rc1"
add_rc_version.py は abeja/version.py が動的に pyproject.toml 記載の version を返してくることを期待していた。
そんなことはなくなるので、、、

2020-11-16 09:30 UTC, toshitanian commented on abeja/version.py
> +VERSION = "2.1.0"
いっそのこと、`VERSION=X.X.X`とかにしたほうがいいかも？
もしくは空にしておいて、echo "VERSION=`poetry version`" > abeja/version.py にするとか

2020-11-16 09:39 UTC, seiro-ogasawara commented on abeja/version.py
> +VERSION = "2.1.0"
値は何でも良いので、空でもアリ 👌 

~Python バージョンを 3.7 以上に上げて `importlib.metadata` が使えるようになれば version.py 自体要らない子になるハズなので、真面目に考えるモチベーションが~

2020-11-16 09:45 UTC, toshitanian commented on abeja/version.py
> +VERSION = "2.1.0"
では、明示的に`VERSION=X.X.X` を任意の値にしておいて欲しいです。`0.0.0` とかでも

2020-11-16 09:52 UTC, ishikawa requested changes

2020-11-16 09:52 UTC, ishikawa commented on .circleci/config.yml
> +      sed -i -e "s/VERSION = \".*\"/VERSION = \"$ver\"/" abeja/version.py
文字列のマッチは `".*?"` にしたいところですが、きっと sed では使えないんですよね...。~~もうこういうのは sed より perl の方がいい気がするけど、~~
sed で書くなら `"[^"]*"` ですかね？　あとは自動 formatter がシングルクォテーションを使うようになったときに動かなくなるので、`["'][^"']*["']` くらいですかね？

2020-11-16 09:52 UTC, ishikawa commented on abeja/version.py
> +VERSION = "2.1.0"
この値は CI で書き換えてるよ、的コメントがほしいです。

2020-11-18 02:15 UTC, seiro-ogasawara commented on .circleci/config.yml
> +      sed -i -e "s/VERSION = \".*\"/VERSION = \"$ver\"/" abeja/version.py
> もうこういうのは sed より perl の方がいい気がするけど

僕は 1行で書けるなら sed/awk で、1行で書けなくなったら perl でって感じですねー。

2020-11-18 02:17 UTC, ishikawa commented on .circleci/config.yml
> +      sed -i -e "s/VERSION = \".*\"/VERSION = \"$ver\"/" abeja/version.py
なるほど。Perl の正規表現に慣れちゃってるので、sed だと機能が足りなすぎて困ること多いんですよね。あと、環境によってオプションとか動作が違うので、Perl の方が互換性高いイメージ。

2020-11-18 02:18 UTC, ishikawa commented on .circleci/config.yml
> +      sed -i -e "s/VERSION = \".*\"/VERSION = \"$ver\"/" abeja/version.py
あ、別に今回は sed で大丈夫です。

2020-11-18 02:27 UTC, seiro-ogasawara commented on .circleci/config.yml
> +      sed -i -e "s/VERSION = \".*\"/VERSION = \"$ver\"/" abeja/version.py
~そうだ Raku を学習しよう~

2020-11-18 02:29 UTC, ishikawa commented on .circleci/config.yml
> +      sed -i -e "s/VERSION = \".*\"/VERSION = \"$ver\"/" abeja/version.py
~~時代は Perl 7 ですよ~~

2020-11-18 02:30 UTC, seiro-ogasawara commented on .circleci/config.yml
> +      sed -i -e "s/VERSION = \".*\"/VERSION = \"$ver\"/" abeja/version.py
~まだ出てないし、どうせ遅れに遅れて来年中リリースとか無理だろうし~

2020-11-18 02:31 UTC, ishikawa approved these changes
LGTM

2020-11-18 02:32 UTC, seiro-ogasawara commented
3fbe3a3 で指摘事項諸々対応いたしました 🙇 

~シェル変数と `"` が組み合わさると `sed` イマイチだった…~

2020-11-18 02:59 UTC, toshitanian approved these changes

2020-11-18 03:25 UTC, seiro-ogasawara commented
:bow:

2020-11-18 03:25 UTC, merged